// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zswzrjsptekiybqnutvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzd3pyanNwdGVraXlicW51dHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDA2MjcsImV4cCI6MjA3NDYxNjYyN30.qsddRuLkUcyJjR2K1IzJf6kkUlgvrtUP6QsCs-7SS5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});