// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zswzrjsptekiybqnutvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzd3pyanNwdGVraXlicW51dHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDA2MjcsImV4cCI6MjA3NDYxNjYyN30.qsddRuLkUcyJjR2K1IzJf6kkUlgvrtUP6QsCs-7SS5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY,
      'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
    }
  }
});

// Log 400 errors for debugging
if (typeof window !== 'undefined') {
  const originalFetch = window.fetch;
  window.fetch = async (...args) => {
    const response = await originalFetch(...args);
    if (response.status === 400 && args[0]?.toString().includes('supabase.co')) {
      console.error('Supabase 400 Error:', {
        url: args[0],
        headers: args[1]?.headers,
        status: response.status
      });
    }
    return response;
  };
}